/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg;

/**
 *
 * @author laboratorio
 */
public class InterfaceCalculadora extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfaceCalculadora.class.getName());

    /**
     * Creates new form InterfaceCalculadora
     */
    double n1, n2;
    String operacao;

    public InterfaceCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPonto = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnMais = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btnVezes = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        txtResultado = new javax.swing.JTextField();
        btnCE = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnBS = new javax.swing.JButton();
        lblValor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnPonto.setText(".");
        btnPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPontoActionPerformed(evt);
            }
        });

        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnMais.setText("+");
        btnMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisActionPerformed(evt);
            }
        });

        btnMenos.setText("-");
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        btnVezes.setText("x");
        btnVezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVezesActionPerformed(evt);
            }
        });

        btnDiv.setText(":");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });

        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });

        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnBS.setText("<-");
        btnBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn0)
                            .addGap(18, 18, 18)
                            .addComponent(btnPonto)
                            .addGap(18, 18, 18)
                            .addComponent(btnIgual)
                            .addGap(18, 18, 18)
                            .addComponent(btnMais))

                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn4)
                            .addGap(18, 18, 18)
                            .addComponent(btn5)
                            .addGap(18, 18, 18)
                            .addComponent(btn6)
                            .addGap(18, 18, 18)
                            .addComponent(btnVezes))

                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn1)
                            .addGap(18, 18, 18)
                            .addComponent(btn2)
                            .addGap(18, 18, 18)
                            .addComponent(btn3)
                            .addGap(18, 18, 18)
                            .addComponent(btnMenos))

                        .addComponent(txtResultado)

                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn7)
                            .addGap(18, 18, 18)
                            .addComponent(btn8)
                            .addGap(20, 20, 20)
                            .addComponent(btn9)
                            .addGap(18, 18, 18)
                            .addComponent(btnDiv))

                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnC)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnBS, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(262, Short.MAX_VALUE))
        );

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCE)
                    .addComponent(btnC)
                    .addComponent(btnBS))

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7)
                    .addComponent(btn8)
                    .addComponent(btn9)
                    .addComponent(btnDiv))

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4)
                    .addComponent(btn5)
                    .addComponent(btn6)
                    .addComponent(btnVezes))

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1)
                    .addComponent(btn2)
                    .addComponent(btn3)
                    .addComponent(btnMenos))

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn0)
                    .addComponent(btnPonto)
                    .addComponent(btnIgual)
                    .addComponent(btnMais))

                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {
        txtResultado.setText(txtResultado.getText() + "6");
    }

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {
        if (txtResultado.getText().isEmpty()) {
            return;
        }

        lblValor.setText(txtResultado.getText() + " :");
        n1 = Double.parseDouble(txtResultado.getText());
        operacao = "Divisao";
        txtResultado.setText("");
    }

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {
        // Não precisa fazer nada aqui
    }

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {
        txtResultado.setText(txtResultado.getText() + "1");
    }

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {
        txtResultado.setText(txtResultado.getText() + "2");
    }

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {
        txtResultado.setText(txtResultado.getText() + "3");
    }

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {
        txtResultado.setText(txtResultado.getText() + "4");
    }

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {
        txtResultado.setText(txtResultado.getText() + "5");
    }

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {
        txtResultado.setText(txtResultado.getText() + "7");
    }

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {
        txtResultado.setText(txtResultado.getText() + "8");
    }

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {
        txtResultado.setText(txtResultado.getText() + "9");
    }

    private void btnPontoActionPerformed(java.awt.event.ActionEvent evt) {
        if (!txtResultado.getText().contains(".")) {
            txtResultado.setText(txtResultado.getText() + ".");
        }
    }

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {
        if (txtResultado.getText().isEmpty() || operacao == null || operacao.isEmpty()) {
            return;
        }

        double resultado;

        n2 = Double.parseDouble(txtResultado.getText());

        if (operacao.equals("Soma")) {
            resultado = n1 + n2;
            lblValor.setText(n1 + " + " + n2 + " =");
        } 
        else if (operacao.equals("Subtracao")) {
            resultado = n1 - n2;
            lblValor.setText(n1 + " - " + n2 + " =");
        } 
        else if (operacao.equals("Multiplicacao")) {
            resultado = n1 * n2;
            lblValor.setText(n1 + " x " + n2 + " =");
        } 
        else if (operacao.equals("Divisao")) {

            if (n2 == 0) {
                txtResultado.setText("Erro");
                lblValor.setText("Divisão por zero");
                return;
            }

            resultado = n1 / n2;
            lblValor.setText(n1 + " : " + n2 + " =");
        } 
        else {
            return;
        }

        txtResultado.setText(String.valueOf(resultado));
    }

    private void btnMaisActionPerformed(java.awt.event.ActionEvent evt) {
        if (txtResultado.getText().isEmpty()) {
            return;
        }

        lblValor.setText(txtResultado.getText() + " +");
        n1 = Double.parseDouble(txtResultado.getText());
        operacao = "Soma";
        txtResultado.setText("");
    }

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {
        if (txtResultado.getText().isEmpty()) {
            return;
        }

        lblValor.setText(txtResultado.getText() + " -");
        n1 = Double.parseDouble(txtResultado.getText());
        operacao = "Subtracao";
        txtResultado.setText("");
    }

    private void btnVezesActionPerformed(java.awt.event.ActionEvent evt) {
        if (txtResultado.getText().isEmpty()) {
            return;
        }

        lblValor.setText(txtResultado.getText() + " x");
        n1 = Double.parseDouble(txtResultado.getText());
        operacao = "Multiplicacao";
        txtResultado.setText("");
    }

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {
        txtResultado.setText(txtResultado.getText() + "0");
    }

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {
        txtResultado.setText("");
    }

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {
        txtResultado.setText("");
        lblValor.setText("");
        n1 = 0;
        n2 = 0;
        operacao = "";
    }

    private void btnBSActionPerformed(java.awt.event.ActionEvent evt) {
        String texto = txtResultado.getText();

        if (!texto.isEmpty()) {
            txtResultado.setText(texto.substring(0, texto.length() - 1));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfaceCalculadora().setVisible(true));
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBS;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMais;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnPonto;
    private javax.swing.JButton btnVezes;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration
}